### ISSUE TITLE
FE | Fix contact page CSS and images in the last section

### ISSUE THREAD

**Issue by M1K1B** [vegaitsourcing/website-horizont-center#106]
Fix CSS by adding Containers, fixing accent text (blue small font), fixing images with flex and percentages (just like in about page).

**Comment by milos1302** [comment]
@M1K1B ovo bi trebalo da valja sada. Mozes li proveriti pa zatvoriti issue ako sam upravu: https://horizont.codeforacause.rs/contact

**Comment by M1K1B** [comment]
@milos1302 ovaj design je dobar ali se ne poklapa sa figma design-om. Da li mislis da treba da napravi kao sto je u figmi ili da zadrimo ovaj?

**Comment by milos1302** [comment]
@M1K1B bitno je samo da je page responsive. Da se nista nije polupalo. Ja sam stavio neke genericke sekcije po uzoru na dizajn, ali nisam primenio dizajn 100%. Dizajneri su kreirali taj page na osnovu povrsnih zahteva, tako da su dosta toga spekulisali, pa nije bitno ako smo neke sekcije izostavili ili ih malo modifikovali i slicno.
Ovo vazi i za Home i za Contact page.
Tek nakon sledeceg sastanka sa udruzenjem cemo da saznamo sta oni zele na tim stranicama i najverovatnije da ce nakon toga te stranice izgledati drugacije (drugaciji redosled i broj sekcija itd.)
Ukratko, bitno je da one sekcije koje su implementirane rade kako treba (ponasaju se kako treba).

**Comment by M1K1B** [comment]
@milos1302 Razumem te sada. Stranica izgleda dobro, zatvoricu ovaj issue.
